import {
  GripVertical,
  BookOpen,
  PencilLine,
  AlertCircle,
  Heart,
  Brain,
  Calendar,
  LayoutDashboard,
  Users,
  MessageCircle,
  LogOut,
  Plus,
  Check,
  Trash2,
  Upload,
  FlaskConical,
  Calculator,
  Globe,
  Landmark,
  Languages,
  Music,
  Dumbbell,
  Palette,
  ChevronLeft,
  ChevronRight,
  LogIn,
  Bike,
  School,
  Sparkles,
  ImageIcon,
  FileText,
  X,
  Target,
  PartyPopper,
  Rocket,
  Loader2,
  ThumbsUp,
  ThumbsDown,
  Meh,
  Eye,
  Menu,
  Sun,
  User,
  TriangleAlert,
  type LucideProps,
} from "lucide-react";

export const ICONS = {
  "book-open": BookOpen,
  "pencil-line": PencilLine,
  "alert-circle": AlertCircle,
  "alert-triangle": TriangleAlert,
  heart: Heart,
  brain: Brain,
  calendar: Calendar,
  dashboard: LayoutDashboard,
  users: Users,
  chat: MessageCircle,
  logout: LogOut,
  plus: Plus,
  check: Check,
  trash: Trash2,
  upload: Upload,
  flask: FlaskConical,
  calculator: Calculator,
  globe: Globe,
  history: Landmark,
  language: Languages,
  music: Music,
  sport: Dumbbell,
  art: Palette,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "log-in": LogIn,
  bike: Bike,
  school: School,
  sparkles: Sparkles,
  image: ImageIcon,
  file: FileText,
  close: X,
  target: Target,
  party: PartyPopper,
  rocket: Rocket,
  loader: Loader2,
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,
  meh: Meh,
  eye: Eye,
  grip: GripVertical,
  menu: Menu,
  sun: Sun,
  user: User,
} as const;

export type IconName = keyof typeof ICONS;

export const SUBJECT_ICON_OPTIONS: IconName[] = [
  "book-open",
  "calculator",
  "flask",
  "globe",
  "history",
  "language",
  "music",
  "sport",
  "art",
];

export function Icon({
  name,
  ...props
}: { name: string } & LucideProps) {
  const Cmp = ICONS[name as IconName] ?? BookOpen;
  return <Cmp {...props} />;
}
